host:
  - name: node1
    addr: localhost
    port: 8881
  - name: node2
    addr: localhost
    port: 8882
  - name: node3
    addr: localhost
    port: 8883
lease:
  master_id: 0
  period: 500
rs:
  x: 3
  n: 3
  qr: 3 
  qw: 3
  f: 0
