nohup bin/zmq_dealer_client 0 &
nohup bin/zmq_dealer_client 1 &
nohup bin/zmq_dealer_client 2 &
nohup bin/zmq_dealer_client 3 &
nohup bin/zmq_dealer_client 4 &
nohup bin/zmq_dealer_client 5 &
nohup bin/zmq_dealer_client 6 &
nohup bin/zmq_dealer_client 7 &
nohup bin/zmq_dealer_client 8 &
nohup bin/zmq_dealer_client 9 &
